import {useEffect,useState,useRef,useCallback} from 'react';
import {api,csrfToken} from './api';
import type {App,Device,Session} from './types';
type Report=(text:string)=>void;
type Monitor={id:string;label:string;width:number;height:number;primary:boolean};
type Settings={computerName:string;autoStart:boolean;port:number;transferDirectory:string;onboarded:boolean;address:string|null};
function allows(s:Session,p:string){return s.desktop||s.permissions.includes(p);}
function Box({title,children}:{title:string;children:React.ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2></div><div className="feature-body">{children}</div></section>;}
function useRows<T>(path:string,enabled:boolean,report:Report,interval=0){const[rows,setRows]=useState<T[]>([]);useEffect(()=>{if(!enabled)return;const stop=new AbortController();let timer:ReturnType<typeof setTimeout>;const read=async()=>{try{const data=await api<T[]>(path,'GET',undefined,stop.signal);if(!stop.signal.aborted)setRows(Array.isArray(data)?data:[]);}catch(e){if(!stop.signal.aborted)report((e as Error).message);}finally{if(interval&&!stop.signal.aborted)timer=setTimeout(read,interval);}};void read();return()=>{stop.abort();clearTimeout(timer);};},[path,enabled,report,interval]);return[rows,setRows]as const;}
export function Power({session,report}:{session:Session;report:Report}){
 const[busy,setBusy]=useState(false),[intent,setIntent]=useState<{id:string;action:string;seconds:number}|null>(null);
 const grant=allows(session,'power.control');
 useEffect(()=>{if(!intent)return;const timer=setInterval(()=>setIntent(old=>old&&old.seconds>1?{...old,seconds:old.seconds-1}:null),1000);return()=>clearInterval(timer);},[intent?.id]);
 const begin=async(action:string)=>{setBusy(true);try{const result=await api<{id:string}>('/power/intents','POST',{action});setIntent({id:result.id,action,seconds:10});}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 const confirm=async()=>{if(!intent)return;setBusy(true);try{await api('/power/confirm','POST',{id:intent.id});setIntent(null);}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 return <Box title="Питание"><div className="actions">{[['lock','Блокировка'],['sleep','Сон'],['hibernate','Гибернация'],['restart','Перезапуск'],['shutdown','Выключить']].map(([action,label])=><button key={action} disabled={!grant||busy} onClick={()=>void begin(action)}>{label}</button>)}</div>{!grant&&<p className="muted small">Разрешение питания выдаётся отдельно на ПК.</p>}{intent&&<div className="confirm-box" role="dialog" aria-modal="true" aria-label="Подтверждение питания"><p>Выполнить «{({'lock':'Блокировка','sleep':'Сон','hibernate':'Гибернация','restart':'Перезапуск','shutdown':'Выключение'} as Record<string,string>)[intent.action]}»?</p><p className="muted">Сохраните документы на ПК. Подтверждение действует {intent.seconds} с.</p><div className="actions"><button className="accent" disabled={busy} onClick={()=>void confirm()}>Подтвердить</button><button onClick={()=>setIntent(null)}>Отмена</button></div></div>}</Box>;
}
export function HomeExtras({session,report}:{session:Session;report:Report}){
 const[media]=useRows<{id:string;title:string;artist:string;status:string}>('/media',allows(session,'media.control'),report,5000);
 const[hotkeys]=useRows<{id:string;label:string}>('/hotkeys',allows(session,'hotkey.invoke'),report);
 const action=async(path:string)=>{try{await api(path,'POST',{});}catch(e){report((e as Error).message);}};
 return <>{media.length>0&&<Box title="Медиа">{media.map(m=><div className="media-row" key={m.id}><div><strong>{m.title||'Медиасессия'}</strong><small>{m.artist} · {m.status}</small></div><div className="actions"><button aria-label="Предыдущий трек" onClick={()=>void action('/media/'+m.id+'/previous')}>Назад</button><button onClick={()=>void action('/media/'+m.id+'/toggle')}>{m.status==='Playing'?'Пауза':'Играть'}</button><button aria-label="Следующий трек" onClick={()=>void action('/media/'+m.id+'/next')}>Далее</button></div></div>)}</Box>}{hotkeys.length>0&&<Box title="Discord · Global Keybind"><div className="actions">{hotkeys.map(k=><button key={k.id} onClick={()=>void action('/hotkeys/'+k.id)}>{k.label}</button>)}</div><p className="muted small">Отправляется настроенная комбинация клавиш. Состояние Mute/Deafen в Discord неизвестно. Микрофон Windows управляется в «Аудио».</p></Box>}<Power session={session} report={report}/></>;
}
export function Clipboard({session,report}:{session:Session;report:Report}){
 const[text,setText]=useState(''),[busy,setBusy]=useState(false);const act=async(read:boolean)=>{setBusy(true);try{if(read){const result=await api<{text:string}>('/clipboard/read','POST',{});setText(result.text);}else await api('/clipboard/write','POST',{text});}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 return <Box title="Буфер обмена · текст / URL"><textarea aria-label="Текст буфера обмена" maxLength={65536} rows={6} value={text} onChange={e=>setText(e.target.value)}/><div className="actions"><button disabled={busy||!allows(session,'clipboard.read')} onClick={()=>void act(true)}>Прочитать с ПК</button><button disabled={busy||!allows(session,'clipboard.write')} onClick={()=>void act(false)}>Записать на ПК</button></div><p className="muted small">Буфер читается только по нажатию. Чтение и запись требуют отдельных разрешений.</p></Box>;
}
export function Remote({session,report}:{session:Session;report:Report}){
 const[monitors]=useRows<Monitor>('/remote/monitors',allows(session,'remote.view'),report),[monitor,setMonitor]=useState(''),[ticket,setTicket]=useState<{id:string;expiresAt:string}|null>(null),[frame,setFrame]=useState(''),[auto,setAuto]=useState(false),[text,setText]=useState(''),[busy,setBusy]=useState(false);const frameRef=useRef('');
 const view=allows(session,'remote.view'),input=allows(session,'remote.input');
 useEffect(()=>{if(!monitor&&monitors.length)setMonitor(monitors.find(x=>x.primary)?.id??monitors[0].id);},[monitors,monitor]);
 const refresh=useCallback(async()=>{if(!monitor||!view)return;setBusy(true);try{let current=ticket;if(!current||Date.parse(current.expiresAt)-Date.now()<3000){current=await api<{id:string;expiresAt:string}>('/remote/sessions','POST',{monitor});setTicket(current);}const result=await fetch('/api/v1/remote/sessions/'+current.id+'/frame',{credentials:'same-origin',cache:'no-store'});if(!result.ok)throw new Error((await result.json().catch(()=>null))?.message??'Экран недоступен.');const next=URL.createObjectURL(await result.blob());if(frameRef.current)URL.revokeObjectURL(frameRef.current);frameRef.current=next;setFrame(next);}catch(e){report((e as Error).message);}finally{setBusy(false);}},[monitor,ticket,view,report]);
 useEffect(()=>{if(!auto||!view)return;const timer=setInterval(()=>{if(!document.hidden&&!busy)void refresh();},2000);return()=>clearInterval(timer);},[auto,view,busy,refresh]);
 useEffect(()=>()=>{if(frameRef.current)URL.revokeObjectURL(frameRef.current);},[]);
 const send=async(body:unknown)=>{if(!ticket||!input)return;try{await api('/remote/sessions/'+ticket.id+'/input','POST',body);}catch(e){report((e as Error).message);}};
 const stop=async()=>{setAuto(false);if(ticket)try{await api('/remote/sessions/'+ticket.id,'DELETE');}catch{}setTicket(null);setFrame('');if(frameRef.current){URL.revokeObjectURL(frameRef.current);frameRef.current='';}};
 return <><Box title="Удалённый экран · снимки"><div className="network-controls"><select aria-label="Монитор" value={monitor} disabled={!view} onChange={e=>{void stop();setMonitor(e.target.value);}}>{monitors.map(m=><option key={m.id} value={m.id}>{m.label} · {m.width}×{m.height}</option>)}</select><button disabled={!view||busy||!monitor} onClick={()=>void refresh()}>Обновить снимок</button><button disabled={!view||!monitor} onClick={()=>{setAuto(!auto);if(!auto)void refresh();}}>{auto?'Пауза':'Обновлять каждые 2 с'}</button><button disabled={!ticket} onClick={()=>void stop()}>Завершить</button></div>{!view&&<p className="muted">Просмотр экрана требует отдельного разрешения на ПК.</p>}<div className="remote-frame">{frame?<img src={frame} alt="Текущий снимок Windows" draggable={false} onClick={e=>{const b=e.currentTarget.getBoundingClientRect();void send({kind:'click',x:(e.clientX-b.left)/b.width,y:(e.clientY-b.top)/b.height});}} onContextMenu={e=>{e.preventDefault();const b=e.currentTarget.getBoundingClientRect();void send({kind:'rightClick',x:(e.clientX-b.left)/b.width,y:(e.clientY-b.top)/b.height});}}/>:<p className="muted">Нажмите «Обновить снимок».</p>}</div><p className="muted small">Касание отправляет click, когда разрешён ввод. UAC, locked screen и elevated окна не обходятся. Это Remote v1 со снимками; видеострим ещё не реализован.</p></Box><Box title="Клавиатура и прокрутка"><textarea rows={3} aria-label="Текст для удалённого ПК" maxLength={512} value={text} onChange={e=>setText(e.target.value)}/><div className="actions"><button disabled={!input||!ticket||!text} onClick={()=>void send({kind:'text',text})}>Ввести текст</button>{['Enter','Escape','Tab','Backspace','ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].map(key=><button key={key} disabled={!input||!ticket} onClick={()=>void send({kind:'key',key})}>{key}</button>)}<button disabled={!input||!ticket} onClick={()=>void send({kind:'scroll',delta:120})}>Scroll ↑</button><button disabled={!input||!ticket} onClick={()=>void send({kind:'scroll',delta:-120})}>Scroll ↓</button></div></Box></>;
}
export function Transfers({session,report}:{session:Session;report:Report}){
 type Item={id:string;name:string;length:number;direction:string;status:string;expiresAt:string};
 const[rows,setRows]=useRows<Item>('/transfers',session.desktop||allows(session,'transfer.send')||allows(session,'transfer.receive'),report,3000),[files,setFiles]=useState<File[]>([]),[progress,setProgress]=useState(0),[busy,setBusy]=useState(false),[path,setPath]=useState(''),[device,setDevice]=useState('');const xhr=useRef<XMLHttpRequest|null>(null);const[devices]=useRows<Device>('/desktop/devices',session.desktop,report);
 useEffect(()=>()=>xhr.current?.abort(),[]);
 const send=async()=>{setBusy(true);try{for(const file of files){const transfer=await api<Item>('/transfers','POST',{name:file.name,length:file.size});await new Promise<void>((resolve,reject)=>{const request=new XMLHttpRequest();xhr.current=request;request.open('PUT','/api/v1/transfers/'+transfer.id+'/content');request.setRequestHeader('X-LC-CSRF',csrfToken());request.upload.onprogress=e=>{if(e.lengthComputable)setProgress(Math.round(100*e.loaded/e.total));};request.onload=()=>request.status>=200&&request.status<300?resolve():reject(new Error('Передача не завершена. Проверьте место и права доступа.'));request.onerror=()=>reject(new Error('Соединение прервано. Повторите передачу.'));request.onabort=()=>{void api('/transfers/'+transfer.id,'DELETE').catch(()=>{});reject(new Error('Передача отменена.'));};request.send(file);});}setFiles([]);setRows(await api('/transfers'));}catch(e){report((e as Error).message);}finally{setBusy(false);setProgress(0);xhr.current=null;}};
 const offer=async()=>{try{await api('/desktop/transfers/offer','POST',{deviceId:device,path});setPath('');setRows(await api('/transfers'));}catch(e){report((e as Error).message);}};
 return <><Box title="Отправить на ПК"><input aria-label="Файлы для передачи" type="file" multiple disabled={busy||!allows(session,'transfer.send')} onChange={e=>setFiles(Array.from(e.target.files??[]))}/><p className="muted small">{files.length} файлов · до 1 ГБ каждый · сохраняются в настроенную папку Downloads/LocalControl.</p><div className="actions"><button className="accent" disabled={busy||!files.length||!allows(session,'transfer.send')} onClick={()=>void send()}>Отправить</button>{busy&&<button onClick={()=>xhr.current?.abort()}>Отменить</button>}<span className="number muted">{busy?progress+'%':''}</span></div></Box>{session.desktop&&<Box title="Отправить с ПК на телефон"><input aria-label="Путь файла для телефона" placeholder="Полный путь к файлу на ПК" value={path} onChange={e=>setPath(e.target.value)}/><select aria-label="Получатель файла" value={device} onChange={e=>setDevice(e.target.value)}><option value="">Выберите подтверждённый телефон</option>{devices.filter(d=>d.permissions.includes('transfer.receive')).map(d=><option key={d.id} value={d.id}>{d.label}</option>)}</select><button disabled={!path||!device} onClick={()=>void offer()}>Поставить в очередь телефона</button><p className="muted small">Файл доступен выбранному устройству 20 минут. Получение должно быть разрешено при подключении.</p></Box>}<Box title="Временная очередь">{rows.length?rows.map(item=><div className="transfer-row" key={item.id}><div><strong>{item.name}</strong><small>{(item.length/1024/1024).toFixed(1)} МБ · {item.direction==='toPc'?'На ПК':'На телефон'} · {item.status}</small></div>{item.direction==='toPhone'&&!session.desktop&&allows(session,'transfer.receive')&&<a className="download-link" href={'/api/v1/transfers/'+item.id+'/download'} download>Скачать</a>}</div>):<p className="muted">Очередь пуста.</p>}</Box></>;
}
export function Hardware({report}:{report:Report}){
 const[data,setData]=useState<{windows:string;user:string;cpu:string;gpus:string[];motherboard:string;powerPlan:string;networks:{name:string;kind:string;addresses:string[];receivedBytes:number;sentBytes:number}[];monitors:Monitor[];warnings:string[]}|null>(null);
 useEffect(()=>{const c=new AbortController();void api<typeof data>('/hardware','GET',undefined,c.signal).then(setData).catch(e=>{if(!c.signal.aborted)report(e.message);});return()=>c.abort();},[report]);
 if(!data)return <Box title="Система"><p className="muted">Читаю информацию Windows…</p></Box>;
 return <><Box title="Компьютер"><dl className="details">{[['Windows',data.windows],['Пользователь',data.user],['CPU',data.cpu],['GPU',data.gpus.join(', ')||'Недоступно'],['Материнская плата',data.motherboard],['План питания',data.powerPlan]].map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl><p className="muted small">Температуры и сенсоры не показываются без надёжного доступного провайдера.</p></Box><Box title="Сетевые адаптеры">{data.networks.map(n=><div className="device-row" key={n.name}><div><strong>{n.name}</strong><small>{n.kind} · {n.addresses.join(' · ')}</small><small>Получено {(n.receivedBytes/1024**3).toFixed(2)} ГБ · отправлено {(n.sentBytes/1024**3).toFixed(2)} ГБ</small></div></div>)}</Box><Box title="Мониторы">{data.monitors.map(m=><p key={m.id}>{m.label} · {m.width}×{m.height}{m.primary?' · основной':''}</p>)}</Box>{data.warnings.map(w=><p className="muted" key={w}>{w}</p>)}</>;
}
export function Startup({report}:{report:Report}){
 type Item={id:string;name:string;source:string;command:string;enabled:boolean;canEdit:boolean;note:string|null};const[rows,setRows]=useRows<Item>('/desktop/startup',true,report);const[busy,setBusy]=useState(false);
 const toggle=async(item:Item)=>{setBusy(true);try{await api('/desktop/startup/'+item.id,'PUT',{enabled:!item.enabled});setRows(await api('/desktop/startup'));}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 return <Box title="Автозапуск Windows">{rows.map(item=><div className="startup-row" key={item.id}><div><strong>{item.name}</strong><small>{item.source} · {item.command}</small>{item.note&&<small>{item.note}</small>}</div><span className="badge">{item.enabled?'Включено':'Выключено'}</span><button disabled={busy||!item.canEdit} onClick={()=>void toggle(item)}>{item.enabled?'Отключить':'Восстановить'}</button></div>)}<p className="muted small">HKCU Run и пользовательская Startup folder сохраняются перед отключением. Общие записи и Task Scheduler — только для чтения; тихого обхода UAC нет.</p></Box>;
}
export function Settings({report,completed}:{report:Report;completed?:()=>void}){
 const[settings,setSettings]=useState<Settings|null>(null),[busy,setBusy]=useState(false),[hotkey,setHotkey]=useState('17,16,77'),[kind,setKind]=useState('discord-mute');
 useEffect(()=>{const stop=new AbortController();void api<Settings>('/desktop/settings','GET',undefined,stop.signal).then(setSettings).catch(e=>{if(!stop.signal.aborted)report(e.message);});return()=>stop.abort();},[report]);
 const save=async()=>{if(!settings)return;setBusy(true);try{await api('/desktop/settings','PUT',{...settings,onboarded:true});completed?.();}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 const configure=async()=>{try{await api('/desktop/hotkeys','PUT',{id:kind,label:kind==='discord-mute'?'Discord · Mute keybind':'Discord · Deafen keybind',keys:hotkey.split(',').map(x=>+x.trim())});report('');}catch(e){report((e as Error).message);}};
 return <>{settings&&<Box title={settings.onboarded?'Настройки':'Добро пожаловать в LocalControl'}><div className="settings-form"><label>Имя компьютера<input maxLength={80} value={settings.computerName} onChange={e=>setSettings({...settings,computerName:e.target.value})}/></label><label>Порт LAN<input type="number" min={1024} max={65535} value={settings.port} onChange={e=>setSettings({...settings,port:+e.target.value})}/></label><label>Папка передачи<input value={settings.transferDirectory} onChange={e=>setSettings({...settings,transferDirectory:e.target.value})}/></label><label className="checkbox"><input type="checkbox" checked={settings.autoStart} onChange={e=>setSettings({...settings,autoStart:e.target.checked})}/>Запускать LocalControl с Windows</label><p className="muted small">LAN включается отдельно в «Подключение». Доступ телефона выдаётся после сверки кода; опасные права выбираются отдельно. Для правила брандмауэра предусмотрен явный elevated helper.</p><button className="accent" disabled={busy} onClick={()=>void save()}>{settings.onboarded?'Сохранить':'Завершить настройку'}</button></div></Box>}<Box title="Discord global keybind"><p className="muted">Сначала создайте комбинацию в Discord → Settings → Keybinds. Здесь укажите те же virtual-key codes. Например 17,16,77 = Ctrl+Shift+M.</p><select value={kind} aria-label="Discord keybind" onChange={e=>setKind(e.target.value)}><option value="discord-mute">Toggle Mute</option><option value="discord-deafen">Toggle Deafen</option></select><input aria-label="Коды комбинации клавиш" value={hotkey} onChange={e=>setHotkey(e.target.value)}/><button onClick={()=>void configure()}>Сохранить комбинацию</button><p className="muted small">LocalControl не читает состояние Discord и не внедряется в его процесс.</p></Box><Box title="Обновление LocalControl"><p className="muted">Установленная версия: 0.3.1. Для обновления скачайте новый Setup.exe и запустите его поверх текущей версии. Этот же файл подходит для первой установки.</p><button onClick={()=>void api('/desktop/downloads','POST',{}).catch(e=>report(e.message))}>Открыть страницу загрузки</button><p className="muted small">Настройки, подтверждённые устройства и полученные файлы сохраняются. Установщик предложит завершить работающий LocalControl перед обновлением.</p></Box></>;
}
export function Applications({session,report}:{session:Session;report:Report}){
 const[apps,setApps]=useRows<App>('/apps',allows(session,'apps.launch'),report,10000),[filter,setFilter]=useState('all'),[query,setQuery]=useState(''),[busy,setBusy]=useState(false),[custom,setCustom]=useState(false),[name,setName]=useState(''),[exe,setExe]=useState(''),[args,setArgs]=useState(''),[cwd,setCwd]=useState(''),[icon,setIcon]=useState('');
 const refresh=async()=>setApps(await api('/apps'));
 const action=async(app:App,kind:string,force=false)=>{if(force&&!window.confirm('Принудительно завершить «'+app.label+'»? Несохранённые данные будут потеряны.'))return;setBusy(true);try{await api('/apps/'+app.id+'/'+kind,'POST',kind==='close'?{force}:{});await refresh();}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 const favorite=async(app:App)=>{try{await api('/desktop/apps/'+app.id,'PUT',{favorite:!app.favorite,name:null});await refresh();}catch(e){report((e as Error).message);}};
 const add=async()=>{setBusy(true);try{await api('/desktop/apps/custom','POST',{name,executable:exe,arguments:args,workingDirectory:cwd,icon:icon||null});setCustom(false);await refresh();}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 const filtered=apps.filter(a=>a.label.toLocaleLowerCase().includes(query.toLocaleLowerCase())&&(filter==='all'||filter==='favorites'&&a.favorite||filter==='running'&&a.running||filter==='games'&&a.category==='Games'||filter==='custom'&&a.source==='Custom'));
 return <><div className="search-bar"><input aria-label="Найти приложение" placeholder="Найти приложение…" value={query} onChange={e=>setQuery(e.target.value)}/>{session.desktop&&<><button disabled={busy} onClick={()=>void api<App[]>('/desktop/apps/rescan','POST',{}).then(setApps).catch(e=>report(e.message))}>Rescan</button><button onClick={()=>setCustom(!custom)}>Добавить exe</button></>}</div><div className="filter-tabs">{[['all','Все'],['favorites','Избранное'],['running','Запущены'],['games','Игры'],['custom','Свои']].map(([id,label])=><button key={id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>{custom&&session.desktop&&<Box title="Добавить своё приложение"><div className="settings-form">{[['Название',name,setName],['Exe',exe,setExe],['Аргументы',args,setArgs],['Рабочая папка',cwd,setCwd],['Иконка exe/ico (необязательно)',icon,setIcon]].map(([label,value,setter])=><label key={label as string}>{label as string}<input value={value as string} onChange={e=>(setter as (x:string)=>void)(e.target.value)}/></label>)}<button className="accent" disabled={busy||!name||!exe} onClick={()=>void add()}>Зарегистрировать на ПК</button></div></Box>}<section className="panel"><div className="panel-heading"><h2>Каталог приложений</h2><span className="muted number">{filtered.length}</span></div>{filtered.slice(0,300).map(a=><div className="app-detail" key={a.id}><img loading="lazy" src={'/api/v1/apps/'+a.id+'/icon'} alt="" width="32" height="32" onError={e=>{e.currentTarget.style.visibility='hidden';}}/><div><strong>{a.label}</strong><small>{a.source} · {a.running===true?'Запущено':a.running===false?'Остановлено':'Состояние неизвестно'}{a.pids?.length?' · PID '+a.pids.join(', '):''}</small></div><div className="actions"><button disabled={busy||!allows(session,'apps.launch')} onClick={()=>void action(a,'launch')}>Запустить</button><button disabled={busy||!allows(session,'apps.close')||a.running!==true} onClick={()=>void action(a,'close')}>Закрыть</button><button disabled={busy||!allows(session,'apps.close')||!allows(session,'apps.launch')} onClick={()=>void action(a,'restart')}>Restart</button><button disabled={busy||!allows(session,'apps.close')||a.running!==true} onClick={()=>void action(a,'close',true)}>Force close</button>{session.desktop&&<button aria-label={'Избранное '+a.label} className={a.favorite?'selected':''} onClick={()=>void favorite(a)}>{a.favorite?'★':'☆'}</button>}</div></div>)}{filtered.length===0&&<div className="empty">Приложения не найдены или запуск не разрешён.</div>}{filtered.length>300&&<p className="muted feature-body">Показаны первые 300. Уточните поиск.</p>}</section></>;
}
