import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { HubConnectionBuilder, LogLevel } from '@microsoft/signalr';
import QRCode from 'qrcode';
import { api, invitationFromFragment, nonce, setCsrf } from './api';
import type { App, Audio, Device, Invitation, Network, Pending, Session, Snapshot } from './types';
import './style.css';
import {Applications,HomeExtras,Remote,Transfers,Clipboard,Hardware,Startup,Settings} from './Features';

const invitation=invitationFromFragment();
const nav=[['home','Обзор','grid'],['apps','Приложения','apps'],['audio','Аудио','audio'],['remote','Экран','apps'],['transfers','Файлы','apps'],['clipboard','Буфер обмена','apps'],['startup','Автозапуск','apps'],['hardware','Система','grid'],['devices','Подключение','phone'],['settings','Настройки','grid'],['more','Ещё','grid']] as const;
type Page=typeof nav[number][0];
function Icon({name}:{name:string}){
 const paths:Record<string,React.ReactNode>={grid:<><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="7" rx="1"/><rect x="3" y="14" width="7" height="7" rx="1"/><rect x="14" y="14" width="7" height="7" rx="1"/></>,apps:<><rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 4v5"/></>,audio:<><path d="M4 10h4l5-5v14l-5-5H4zM17 8a6 6 0 0 1 0 8M20 5a10 10 0 0 1 0 14"/></>,phone:<><rect x="6" y="2" width="12" height="20" rx="2"/><path d="M10 18h4"/></>,arrow:<path d="m9 5 7 7-7 7"/>,mic:<><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10v2a7 7 0 0 0 14 0v-2M12 19v3M8 22h8"/></>,moon:<path d="M20 14A9 9 0 0 1 10 3a9 9 0 1 0 10 11Z"/>,play:<path d="m8 4 12 8-12 8Z"/>,close:<path d="m6 6 12 12M18 6 6 18"/>,check:<path d="m4 12 5 5L20 6"/>,refresh:<><path d="M20 7V3l-4 1M4 17v4l4-1M20 3a9 9 0 0 0-15 5M4 21a9 9 0 0 0 15-5"/></>};
 return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name]??paths.grid}</svg>;
}
function Pairing({connected}:{connected:(session:Session)=>void}){
 const [label,setLabel]=useState('Телефон'),[ticket,setTicket]=useState<{id:string;secret:string;code:string;expiresAt:string}|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 useEffect(()=>{
  if(!ticket)return;
  const stop=new AbortController();let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{
   if(Date.now()>Date.parse(ticket.expiresAt)){setError('Время подключения истекло. Откройте новый QR на ПК.');setTicket(null);return;}
   try{const result=await api<{status:string}>('/pairing/claim','POST',{id:ticket.id,secret:ticket.secret},stop.signal);
    if(result.status==='approved'){connected(await api<Session>('/session','GET',undefined,stop.signal));return;}
    if(result.status==='rejected'){setError('Запрос отклонён на ПК.');setTicket(null);return;}
    timer=setTimeout(poll,1500);
   }catch(e){if(!stop.signal.aborted){setError((e as Error).message);setTicket(null);}}
  };timer=setTimeout(poll,1000);return()=>{stop.abort();clearTimeout(timer);};
 },[ticket,connected]);
 const request=async()=>{if(!invitation)return;setBusy(true);setError('');try{setTicket(await api('/pairing/requests','POST',{invite:invitation,nonce:nonce(),label:label.trim()}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
 return <main className="pair-screen"><div className="pair-card"><div className="brand"><img className="brand-mark" src="/icon.svg" alt=""/>LocalControl</div><p className="eyebrow">ВАШ ПК · В ВАШЕЙ СЕТИ</p><h1>{ticket?'Сверьте код на ПК':'Подключение телефона'}</h1>
 {ticket?<><div className="pair-code">{ticket.code}</div><p className="muted">Подтвердите этот код в LocalControl на компьютере. Имя телефона само по себе не подтверждает его личность.</p><div className="waiting"><span className="dot"/> Ожидание подтверждения</div></>:invitation?<><p className="muted">ПК должен быть включён. Для подключения потребуется подтверждение в его окне.</p><label>Название устройства<input autoComplete="off" maxLength={80} value={label} onChange={e=>setLabel(e.target.value)}/></label><button className="accent wide" disabled={busy||!label.trim()} onClick={request}>{busy?'Создаю запрос…':'Запросить подключение'}</button></>:<p className="muted">Откройте «Подключение» в LocalControl на ПК и сканируйте QR телефоном. При завершении сессии потребуется новый QR.</p>}
 {error&&<p className="error" role="alert">{error}</p>}<p className="transport-note">HTTP · домашняя сеть · сессия 30 минут<br/>Данные передаются без шифрования. Используйте доверенную сеть.</p></div></main>;
}
function AudioRow({item,allowed,report}:{item:Audio;allowed:boolean;report:(message:string)=>void}){
 const [volume,setVolume]=useState(Math.round(item.volume*100)),[busy,setBusy]=useState(false);const dragging=useRef(false);
 useEffect(()=>{if(!dragging.current&&!busy)setVolume(Math.round(item.volume*100));},[item]);
 const commit=async(value:number)=>{dragging.current=false;setBusy(true);try{await api('/audio/'+item.id,'PUT',{volume:value/100});}catch(e){setVolume(Math.round(item.volume*100));report((e as Error).message);}finally{setBusy(false);}};
 const mute=async()=>{setBusy(true);try{await api('/audio/'+item.id,'PUT',{muted:!item.muted});}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 return <div className={'audio-row '+(item.muted?'is-muted':'')}><span className="row-icon"><Icon name={item.kind==='microphone'?'mic':item.kind==='session'?'apps':'audio'}/></span><div className="audio-label"><strong>{item.label}</strong><small>{item.kind==='microphone'?'Микрофон Windows':item.kind==='session'?'Аудиосессия приложения':item.isDefault?'Вывод по умолчанию':'Устройство вывода'}</small></div><input aria-label={'Громкость '+item.label} type="range" min="0" max="100" value={volume} disabled={!allowed||busy} onPointerDown={()=>{dragging.current=true;}} onChange={e=>setVolume(+e.target.value)} onPointerUp={e=>void commit(+(e.target as HTMLInputElement).value)} onPointerCancel={()=>{dragging.current=false;setVolume(Math.round(item.volume*100));}} onKeyUp={e=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Home','End','PageUp','PageDown'].includes(e.key))void commit(+(e.target as HTMLInputElement).value);}}/><span className="volume number">{volume}%</span><button className={'icon-button '+(item.muted?'selected':'')} aria-label={(item.muted?'Включить ':'Выключить ')+item.label} title={item.muted?'Включить звук':'Выключить звук'} disabled={!allowed||busy} onClick={mute}><Icon name={item.muted?'close':item.kind==='microphone'?'mic':'audio'}/></button></div>;
}
function Panel({title,aside,children}:{title:string;aside?:React.ReactNode;children:React.ReactNode}){return <section className="panel"><div className="panel-heading"><h2>{title}</h2>{aside}</div>{children}</section>;}
function formatBytes(value:number){return(value/1024**3).toFixed(1)+' ГБ';}
function uptime(seconds:number){return Math.floor(seconds/3600)+' ч '+Math.floor(seconds%3600/60)+' мин';}
function Devices({report}:{report:(message:string)=>void}){
 const [network,setNetwork]=useState<Network|null>(null),[address,setAddress]=useState(''),[invite,setInvite]=useState<Invitation|null>(null),[qr,setQr]=useState(''),[pending,setPending]=useState<Pending[]>([]),[devices,setDevices]=useState<Device[]>([]),[busy,setBusy]=useState(false),[now,setNow]=useState(Date.now()),[grants,setGrants]=useState<Record<string,string[]>>({});
 useEffect(()=>{const stop=new AbortController();let timer:ReturnType<typeof setTimeout>;const poll=async()=>{try{const[n,p,d]=await Promise.all([api<Network>('/desktop/network','GET',undefined,stop.signal),api<Pending[]>('/desktop/pairing/pending','GET',undefined,stop.signal),api<Device[]>('/desktop/devices','GET',undefined,stop.signal)]);if(!stop.signal.aborted){setNetwork(n);setAddress(old=>old||n.addresses[0]||'');setPending(p);setDevices(d);setNow(Date.now());}}catch(e){if(!stop.signal.aborted)report((e as Error).message);}finally{if(!stop.signal.aborted)timer=setTimeout(poll,2000);}};void poll();return()=>{stop.abort();clearTimeout(timer);};},[report]);
 useEffect(()=>{setQr('');if(!invite)return;let alive=true;void QRCode.toDataURL(invite.url,{width:256,margin:2,color:{dark:'#15171a',light:'#ffffff'}}).then(value=>{if(alive)setQr(value);}).catch(()=>report('Не удалось построить QR. Откройте адрес вручную.'));return()=>{alive=false;};},[invite,report]);
 const act=async(work:()=>Promise<unknown>)=>{setBusy(true);try{await work();}catch(e){report((e as Error).message);}finally{setBusy(false);}};
 const changeNetwork=()=>void act(async()=>{const disabling=!!network?.url;if(!disabling&&!window.confirm('Включить управление по HTTP в домашней сети? Данные передаются без шифрования. Разрешайте доступ в брандмауэре только для частной сети.'))return;await api('/desktop/network','PUT',{address:disabling?null:address,port:(await api<{port:number}>('/desktop/settings')).port});setInvite(null);setNetwork(await api('/desktop/network'));});
 const open=()=>void act(async()=>setInvite(await api('/desktop/pairing/open','POST',{})));
 const decide=(id:string,approve:boolean)=>void act(async()=>{await api('/desktop/pairing/'+id+'/decide','POST',{approve,permissions:grants[id]??['status.read','audio.control','apps.launch']});setPending(old=>old.filter(x=>x.id!==id));setDevices(await api('/desktop/devices'));});
 const revoke=(device:Device)=>{if(window.confirm('Отозвать доступ «'+device.label+'»? Текущая сессия будет закрыта.'))void act(async()=>{await api('/desktop/devices/'+device.id,'DELETE');setDevices(old=>old.filter(x=>x.id!==device.id));});};
 const remaining=invite?Math.max(0,Math.ceil((Date.parse(invite.expiresAt)-now)/1000)):0;
 return <><Panel title="Локальная сеть" aside={<span className={'badge '+(network?.url?'good':'')}>{network?.url?'LAN включён':'LAN выключен'}</span>}><div className="network-body"><p className="muted">Телефон подключается напрямую к ПК. После выхода из LocalControl сервер останавливается.</p><div className="network-controls"><select aria-label="Адрес LAN" disabled={busy||!!network?.url} value={address} onChange={e=>setAddress(e.target.value)}>{network?.addresses.map(a=><option key={a}>{a}</option>)}</select><button className={network?.url?'':'accent'} disabled={busy||!address} onClick={changeNetwork}>{network?.url?'Выключить LAN':'Включить LAN'}</button><button disabled={busy||!network?.url} onClick={open}>Подключить телефон</button></div>{network?.url&&<p className="number lan-address">{network.url}</p>}<p className="muted small">Порт настраивается в «Настройках» · IPv4 · HTTP. Если телефон не открывает страницу, разрешите LocalControl в брандмауэре для частной сети. Инструкция прилагается к исходникам.</p></div></Panel>
 {invite&&<Panel title={remaining?'Сканируйте QR на телефоне':'QR истёк'} aside={<span className="number muted">{remaining} с</span>}><div className="invitation">{qr&&remaining>0&&<img src={qr} width="208" height="208" alt="QR подключения телефона"/>}<div><p>Сверьте шестизначный код после запроса и подтвердите устройство здесь, на ПК.</p>{remaining>0&&<a className="invite-link" href={invite.url} onClick={e=>e.preventDefault()}>{invite.url}</a>}<p className="muted small">Запрос не выдаёт доступ до вашего подтверждения.</p></div></div></Panel>}
 {pending.map(p=><Panel key={p.id} title={p.label} aside={<span className="badge">Запрос подключения</span>}><div className="network-body"><p className="pair-code inline">{p.code}</p><p className="muted">Сверьте этот код с экраном телефона. Адрес: {p.peer}</p><div className="permissions">{[['audio.control','Управление аудио'],['apps.launch','Запуск приложений'],['apps.close','Закрытие приложений'],['media.control','Медиакнопки'],['transfer.send','Отправка на ПК'],['transfer.receive','Получение файлов'],['clipboard.read','Чтение буфера'],['clipboard.write','Запись буфера'],['power.control','Питание ПК'],['remote.view','Просмотр экрана'],['remote.input','Ввод на ПК'],['hotkey.invoke','Discord keybind']].map(([permission,label])=><label key={permission}><input type="checkbox" checked={(grants[p.id]??['status.read','audio.control','apps.launch']).includes(permission)} onChange={e=>setGrants(old=>{const values=old[p.id]??['status.read','audio.control','apps.launch'];return{...old,[p.id]:e.target.checked?[...new Set([...values,permission,...(permission==='remote.input'?['remote.view']:[])])]:values.filter(x=>x!==permission&&(permission!=='remote.view'||x!=='remote.input'))};})}/>{label}</label>)}</div><div className="actions"><button className="accent" disabled={busy} onClick={()=>decide(p.id,true)}>Код совпадает · разрешить</button><button disabled={busy} onClick={()=>decide(p.id,false)}>Отклонить</button></div></div></Panel>)}
 <Panel title="Подтверждённые устройства" aside={<span className="muted number">{devices.length}</span>}>{devices.length?devices.map(d=><div className="device-row" key={d.id}><span className="row-icon"><Icon name="phone"/></span><div><strong>{d.label}</strong><small>Статус{d.permissions.includes('audio.control')?' · Аудио':''}{d.permissions.includes('apps.launch')?' · Запуск':''} · HTTP-сессия до 30 минут</small></div><button disabled={busy} onClick={()=>revoke(d)}>Отозвать</button></div>):<div className="empty">Подключённых устройств пока нет.</div>}</Panel></>;
}
function Workspace({session,onEnd}:{session:Session;onEnd:()=>void}){
 const[page,setPage]=useState<Page>('home'),[state,setState]=useState<Snapshot|null>(null),[apps,setApps]=useState<App[]>([]),[query,setQuery]=useState(''),[error,setError]=useState(''),[live,setLive]=useState(false),[online,setOnline]=useState(false),[theme,setTheme]=useState(()=>localStorage.getItem('lc-theme')??'dark'),[launching,setLaunching]=useState<string|null>(null);
 const report=React.useCallback((message:string)=>setError(message),[]);
 const accept=React.useCallback((value:Snapshot)=>{setOnline(true);setState(old=>!old||value.revision>old.revision?value:old);},[]);
 useEffect(()=>{const media=matchMedia('(prefers-color-scheme: light)');const apply=()=>{document.documentElement.dataset.theme=theme==='system'?(media.matches?'light':'dark'):theme;};apply();media.addEventListener('change',apply);localStorage.setItem('lc-theme',theme);return()=>media.removeEventListener('change',apply);},[theme]);
 useEffect(()=>{
  const stop=new AbortController();let disposed=false,timer:ReturnType<typeof setTimeout>;
  const connection=new HubConnectionBuilder().withUrl('/hubs/state').configureLogging(LogLevel.None).withAutomaticReconnect([0,2000,5000,10000]).build();
  connection.on('state',accept);connection.onreconnecting(()=>setLive(false));connection.onreconnected(()=>{setLive(true);void api<Snapshot>('/state').then(accept).catch(e=>report(e.message));});connection.onclose(()=>{setLive(false);});
  const poll=async()=>{try{accept(await api<Snapshot>('/state','GET',undefined,stop.signal));}catch(e){if(!stop.signal.aborted){setOnline(false);report((e as Error).message);}}finally{if(!stop.signal.aborted)timer=setTimeout(poll,document.hidden?15000:5000);}};
  void connection.start().then(()=>{if(disposed)void connection.stop();else setLive(true);}).catch(()=>setLive(false));void poll();
  if(session.desktop||session.permissions.includes('apps.launch')){const readApps=()=>void api<App[]>('/apps','GET',undefined,stop.signal).then(value=>{if(!stop.signal.aborted)setApps(Array.isArray(value)?value:[]);}).catch(e=>{if(!stop.signal.aborted)report(e.message);});readApps();}
  const ended=()=>onEnd();window.addEventListener('lc-session-ended',ended);
  return()=>{disposed=true;stop.abort();clearTimeout(timer);window.removeEventListener('lc-session-ended',ended);void connection.stop();};
 },[accept,report,onEnd,session.permissions]);
 useEffect(()=>{if(session.desktop)void api<{onboarded:boolean}>('/desktop/settings').then(value=>{if(value&&value.onboarded===false)setPage('settings');}).catch(()=>{});},[session.desktop]);
 const launch=async(app:App)=>{setLaunching(app.id);try{await api('/apps/'+app.id+'/launch','POST',{});report('');}catch(e){report((e as Error).message);}finally{setLaunching(null);}};
 const allowedAudio=session.desktop||session.permissions.includes('audio.control');
 const pages=session.desktop?nav.filter(x=>x[0]!=='more'):nav.filter(x=>['home','apps','audio','remote','more'].includes(x[0]));
 const mobilePages=nav.filter(x=>['home','apps','audio','remote','more'].includes(x[0]));
 const m=state?.machine;
 const meter=(title:string,value:string,percent?:number|null,detail?:string)=><div className="metric"><p>{title}</p><strong className="number">{value}</strong>{percent!=null&&<div className="meter"><span style={{width:Math.max(0,Math.min(100,percent))+'%'}}/></div>}<small>{detail}</small></div>;
 const output=state?.audio.filter(x=>x.kind!=='session')??[];
 const appGrid=(items:App[])=>items.length?<div className="app-grid">{items.map(a=><button className="app-tile" key={a.id} disabled={launching!==null} onClick={()=>void launch(a)}><span className="app-monogram">{a.label.slice(0,2).toUpperCase()}</span><span><strong>{a.label}</strong><small>{launching===a.id?'Запуск…':a.source}</small></span><Icon name="play"/></button>)}</div>:<div className="empty">{session.permissions.includes('apps.launch')?'Приложения не найдены.':'Запуск приложений не разрешён на ПК.'}</div>;
 return <div className="shell"><aside className="sidebar"><div className="brand"><img className="brand-mark" src="/icon.svg" alt=""/>LocalControl</div><p className="eyebrow">РАБОЧЕЕ ПРОСТРАНСТВО</p><nav>{pages.map(([key,label,icon])=><button className={page===key?'active':''} key={key} onClick={()=>setPage(key)}><Icon name={icon}/>{label}</button>)}</nav><div className="sidebar-bottom"><span className="dot"/> {session.desktop?'Этот компьютер':'Подтверждённый телефон'}<small>LocalControl · 0.3.1</small></div></aside><div className="main"><header><div className="host"><span className={'status-dot '+(online?'online':'')}/><strong>{m?.name??'Подключение к ПК…'}</strong><span className="badge desktop-only">{session.desktop?'Локально':'LAN'}</span></div><div className="header-actions"><span className="muted small desktop-only">{online?(live?'Live':'Обновление по запросу'):'Нет связи'}</span><button className="icon-button" title="Сменить тему" aria-label="Сменить тему" onClick={()=>setTheme(theme==='dark'?'light':theme==='light'?'system':'dark')}><Icon name="moon"/></button>{!session.desktop&&<button onClick={()=>void api('/session/logout','POST',{}).finally(onEnd)}>Выйти</button>}</div></header><main className="content"><div className="page-title"><div><p className="eyebrow">LOCALCONTROL</p><h1>{nav.find(x=>x[0]===page)?.[1]}</h1><p className="muted">{page==='home'?'Состояние компьютера и быстрые действия':page==='apps'?'Приложения, зарегистрированные на этом ПК':page==='audio'?'Устройства Windows и активные аудиосессии':'Управление доступом из домашней сети'}</p></div>{state&&<span className="updated number desktop-only">{new Date(state.at).toLocaleTimeString('ru-RU')}</span>}</div>
 {error&&<div className="notice error" role="alert"><span>{error}</span><button aria-label="Закрыть сообщение" className="icon-button" onClick={()=>setError('')}><Icon name="close"/></button></div>}
 {state?.warnings.map((w,i)=><div className="notice" key={i}>{w}</div>)}
 {page==='home'&&<><div className="metrics">{meter('Процессор',m?.cpuPercent==null?'—':Math.round(m.cpuPercent)+'%',m?.cpuPercent,'Общая загрузка CPU')}{meter('Оперативная память',m?formatBytes(m.memoryUsedBytes):'—',m?100*m.memoryUsedBytes/m.memoryTotalBytes:undefined,m?'из '+formatBytes(m.memoryTotalBytes):'Ожидание данных')}{meter('Время работы',m?uptime(m.uptimeSeconds):'—',undefined,'С последнего запуска Windows')}</div><div className="home-grid"><Panel title="Аудиоустройства" aside={<button className="text-button" onClick={()=>setPage('audio')}>Все сессии <Icon name="arrow"/></button>}>{output.length?output.filter(x=>x.isDefault).map(a=><AudioRow key={a.id} item={a} allowed={allowedAudio} report={report}/>):<div className="empty">{state?'Аудиоустройства недоступны.':'Читаю состояние Windows…'}</div>}</Panel><Panel title="Диски">{m?.disks.map(d=><div className="disk" key={d.label}><div><strong>{d.label}</strong><span className="muted number">{formatBytes(d.freeBytes)} свободно</span></div><div className="meter"><span style={{width:(100-100*d.freeBytes/d.totalBytes)+'%'}}/></div><small>из {formatBytes(d.totalBytes)}</small></div>)??<div className="empty">Ожидание данных</div>}</Panel></div><Panel title="Быстрый запуск" aside={<button className="text-button" onClick={()=>setPage('apps')}>Все приложения <Icon name="arrow"/></button>}>{appGrid((apps.some(x=>x.favorite)?apps.filter(x=>x.favorite):apps).slice(0,6))}</Panel><HomeExtras session={session} report={report}/></>}
 {page==='audio'&&<><Panel title="Устройства вывода">{output.filter(x=>x.kind==='output').map(a=><AudioRow key={a.id} item={a} allowed={allowedAudio} report={report}/>)}</Panel><Panel title="Микрофоны">{output.filter(x=>x.kind==='microphone').map(a=><AudioRow key={a.id} item={a} allowed={allowedAudio} report={report}/>)}</Panel><Panel title="Приложения">{state?.audio.some(x=>x.kind==='session')?state.audio.filter(x=>x.kind==='session').map(a=><AudioRow key={a.id} item={a} allowed={allowedAudio} report={report}/>):<div className="empty">Активных аудиосессий нет.</div>}</Panel><p className="muted small">Микрофон меняется на уровне Windows. Состояние mute в Discord здесь не определяется.</p></>}
 {page==='apps'&&<Applications session={session} report={report}/>}
 {page==='remote'&&<Remote session={session} report={report}/>}
 {page==='transfers'&&<Transfers session={session} report={report}/>}
 {page==='clipboard'&&<Clipboard session={session} report={report}/>}
 {page==='hardware'&&<Hardware report={report}/>}
 {page==='startup'&&session.desktop&&<Startup report={report}/>}
 {page==='settings'&&session.desktop&&<Settings report={report} completed={()=>setPage('home')}/>}
 {page==='more'&&<div className="more-menu">{nav.filter(x=>['transfers','clipboard','hardware'].includes(x[0])||session.desktop&&['startup','devices','settings'].includes(x[0])).map(([key,label,icon])=><button key={key} onClick={()=>setPage(key)}><Icon name={icon}/>{label}<Icon name="arrow"/></button>)}</div>}
 {page==='devices'&&session.desktop&&<Devices report={report}/>}
 </main></div><nav className="bottom-nav">{mobilePages.map(([key,label,icon])=><button key={key} className={page===key?'active':''} onClick={()=>setPage(key)}><Icon name={icon}/><span>{label}</span></button>)}</nav></div>;
}
function Root(){const[session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true);const connected=React.useCallback((s:Session)=>{setCsrf(s.csrf);setSession(s);},[]);const ended=React.useCallback(()=>{setCsrf('');setSession(null);},[]);useEffect(()=>{let alive=true;void api<Session>('/session').then(s=>{if(alive)connected(s);}).catch(()=>{}).finally(()=>{if(alive)setLoading(false);});return()=>{alive=false;};},[connected]);if(loading)return <div className="loading"><img className="brand-mark" src="/icon.svg" alt=""/><p>Подключение к LocalControl…</p></div>;return session?<Workspace session={session} onEnd={ended}/>:<Pairing connected={connected}/>;}
createRoot(document.getElementById('root')!).render(<Root/>);
